import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Nebula Pro Laptop',
    price: 1499,
    category: 'ELECTRONICS',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=800',
    description: 'Precision engineered for high-performance computing.',
    isNew: true,
    sizes: ['14"', '16"'],
    colors: ['Space Gray', 'Silver'],
  },
  {
    id: '2',
    name: 'Classic Linen Shirt',
    price: 85,
    category: 'FASHION',
    image: 'https://images.unsplash.com/photo-1594932224011-041d83b1d977?auto=format&fit=crop&q=80&w=800',
    description: 'Breathable linen for effortless summer elegance.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Sand', 'Sky Blue'],
  },
  {
    id: '3',
    name: 'Chrono Diver Watch',
    price: 450,
    category: 'WATCHES',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800',
    description: 'Automatic movement with 200m water resistance.',
    isNew: true,
    sizes: ['42mm'],
    colors: ['Silver/Black', 'Silver/Blue'],
  },
  {
    id: '4',
    name: 'Luna Silk Scarf',
    price: 120,
    category: 'ACCESSORIES',
    image: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&q=80&w=800',
    description: '100% mulberry silk with hand-rolled edges.',
    sizes: ['One Size'],
    colors: ['Emerald', 'Midnight Blue'],
  },
  {
    id: '5',
    name: 'Aurelia Gold Hoop',
    price: 320,
    category: 'JEWELRY',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=800',
    description: '18k solid gold hoops with a timeless polished finish.',
    isNew: true,
    sizes: ['Small', 'Medium'],
    colors: ['Gold'],
  },
  {
    id: '6',
    name: 'Zenith Smart Headphones',
    price: 399,
    category: 'ELECTRONICS',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800',
    description: 'Immersive sound with active noise cancellation.',
    sizes: ['One Size'],
    colors: ['Charcoal', 'Bone'],
  },
  {
    id: '7',
    name: 'Minimalist Leather Belt',
    price: 65,
    category: 'ACCESSORIES',
    image: 'https://images.unsplash.com/photo-1624222247344-550fb8ec5521?auto=format&fit=crop&q=80&w=800',
    description: 'Full-grain Italian leather with a brushed nickel buckle.',
    sizes: ['30', '32', '34', '36'],
    colors: ['Black', 'Tan'],
  },
  {
    id: '8',
    name: 'Elysian Diamond Ring',
    price: 1200,
    category: 'JEWELRY',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800',
    description: 'Sustainable lab-grown diamond set in 14k white gold.',
    sizes: ['6', '7', '8'],
    colors: ['White Gold'],
  },
  {
    id: '9',
    name: 'Heritage Trench Coat',
    price: 550,
    category: 'FASHION',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800',
    description: 'Weather-resistant gabardine with a classic double-breasted cut.',
    sizes: ['S', 'M', 'L'],
    colors: ['Beige', 'Black'],
  },
  {
    id: '10',
    name: 'Aether Smart Rings',
    price: 249,
    category: 'ELECTRONICS',
    image: 'https://images.unsplash.com/photo-1610940882244-1fbcfe92fca1?auto=format&fit=crop&q=80&w=800',
    description: 'Health tracking packed into a sleek titanium ring.',
    isNew: true,
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Stealth Black', 'Brushed Silver'],
  },
  {
    id: '11',
    name: 'Nova Ceramic Vase',
    price: 85,
    category: 'HOME',
    image: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&q=80&w=800',
    description: 'Architectural ceramic piece with a textured glaze.',
    sizes: ['Standard'],
    colors: ['Terracotta', 'Cream'],
  },
  {
    id: '12',
    name: 'Onyx Fountain Pen',
    price: 145,
    category: 'ACCESSORIES',
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=800',
    description: 'Hand-crafted resin body with a 14k gold nib.',
    sizes: ['One Size'],
    colors: ['Midnight'],
  }
];
